inherit_gem:
  syntax_tree: config/rubocop.yml

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  SuggestExtensions: false
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
  - 'vendor/**/*'
  - 'yard/**/*'
  - 'tmp/**/*'

Gemspec/RequiredRubyVersion:
  Enabled: false

Layout/LineLength:
  Max: 80

Lint/AmbiguousBlockAssociation:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FormatString:
  EnforcedStyle: percent

Style/FormatStringToken:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
