name: Main
on:
- push
- pull_request_target
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
    - uses: actions/checkout@master
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        ruby-version: '3.1'
    - name: Lint and test
      run: |
        bundle exec rubocop --parallel
        bundle exec rake test

  valgrind:
    name: Valgrind
    runs-on: ubuntu-latest
    steps:
    - run: sudo apt-get install -y valgrind
    - uses: actions/checkout@master
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        bundler-cache: true
    - run: bundle exec rake test:valgrind

  automerge:
    name: AutoMerge
    needs: [ci, valgrind]
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request_target' && github.actor == 'dependabot[bot]'
    steps:
    - uses: actions/github-script@v3
      with:
        script: |
          github.pulls.merge({
            owner: context.payload.repository.owner.login,
            repo: context.payload.repository.name,
            pull_number: context.payload.pull_request.number
          })
